name: "Step 1"

on:
  workflow_call:

jobs:
  sleep:
    name: "sleep 5 sec"
    runs-on: ubuntu-latest
    steps:
      - name: Run sleep 5 sec
        run: sleep 5

      - uses: styfle/cancel-workflow-action@0.12.1
        with:
          workflow_id: "step2"
